#!/usr/bin/env python3
"""
Zenodo 上传脚本 — 知识卡片独立 DOI 发布

用法:
  # 设置 Token（首次）
  export ZENODO_TOKEN=your_token_here
  
  # 上传单张卡片
  python3 zenodo_upload.py cards/10.1038_s41586-019-1799-6.yaml
  
  # 也可以从环境变量读取
  ZENODO_TOKEN=xxx python3 zenodo_upload.py <yaml_path>
  
流程:
  1. 读取 YAML 卡片 → 提取 bibliographic 元数据
  2. 创建 Zenodo 草稿 → 获得临时 ID
  3. 上传卡片 YAML + 附带的 JSON 到草稿
  4. 发布 → 获得永久 DOI
  5. 将 DOI 写回到卡片 YAML 的 zenodo_doi 字段
"""

import os, sys, json, yaml, requests
from datetime import datetime

ZENODO_BASE = "https://zenodo.org/api/deposit/depositions"

def get_token():
    """获取 Zenodo API Token"""
    token = os.environ.get("ZENODO_TOKEN")
    if not token:
        print("❌ 请设置 ZENODO_TOKEN 环境变量")
        print("   在 https://zenodo.org/account/settings/applications/tokens/new/ 生成")
        sys.exit(1)
    return token

def load_card(path):
    """加载知识卡片 YAML"""
    with open(path) as f:
        card = yaml.safe_load(f)
    
    # 从 card 中提取 bibliographic 或 paper 字段
    bib = card.get("bibliographic", card.get("paper", {}))
    
    # 提取元数据
    title = bib.get("title", card.get("paper", {}).get("title", "Unknown"))
    doi = bib.get("doi", card.get("paper", {}).get("doi", ""))
    
    # 构建作者列表
    authors = []
    if "authors" in bib and isinstance(bib["authors"], list):
        for a in bib["authors"]:
            authors.append({"name": a})
    elif "authors_short" in bib:
        authors.append({"name": bib["authors_short"]})
    elif "authors" in card.get("paper", {}):
        authors.append({"name": card["paper"]["authors"]})
    
    # 关键词
    keywords = card.get("paper", {}).get("keywords", ["academic paper", "knowledge extraction"])
    
    # 描述
    description = f"""# 🌍 人类知识提取开源计划 — 文献知识卡片

## 论文信息

- **标题**: {title}
- **DOI**: {doi}
- **来源**: Semantic Scholar / 全文分析

## 卡片内容

本文档是对已发表学术论文的深度知识提取和结构化分析，包含 8 个章节：
1. 摘要（分析性重述）
2. 引言（逐段 CARDS 分析）
3. 结果（完整数据）
4. 讨论（理论体系分析）
5. 方法（完整复现）
6. 补充数据（结构化表格）
7. 引用分析（四层框架）
8. 活卡片（进展追踪）

生成时间: {datetime.now().strftime('%Y-%m-%d')}
生成平台: Synthos · paper-knowledge-base v2.0
"""
    
    return {
        "title": f"[Knowledge Card] {title[:200]}",
        "doi": doi,
        "authors": authors,
        "keywords": keywords,
        "description": description,
        "card_yaml_path": path,
        "card_data": card,
    }

def list_existing(token, title):
    """检查是否已存在相同标题的草稿"""
    headers = {"Authorization": f"Bearer {token}"}
    r = requests.get(ZENODO_BASE, headers=headers, params={"q": title[:100]})
    if r.status_code == 200:
        existing = r.json()
        for dep in existing:
            if dep.get("title") == title and dep.get("state") != "done":
                return dep.get("id")
    return None

def create_deposition(token, meta):
    """创建 Zenodo 草稿"""
    headers = {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}
    
    data = {
        "metadata": {
            "title": meta["title"],
            "upload_type": "publication",
            "publication_type": "report",
            "description": meta["description"],
            "creators": meta["authors"],
            "keywords": meta["keywords"],
            "access_right": "open",
            "license": "MIT",
            "communities": [{"identifier": "zenodo"}],
            "related_identifiers": [
                {
                    "relation": "isSupplementTo",
                    "identifier": meta["doi"],
                    "resource_type": "publication-article"
                }
            ],
            "notes": "Generated by Synthos paper-knowledge-base skill. Full paper knowledge reproduction - copyright safe under fair use."
        }
    }
    
    r = requests.post(ZENODO_BASE, headers=headers, data=json.dumps(data))
    if r.status_code != 201:
        print(f"❌ 创建草稿失败: {r.status_code}")
        print(r.text[:500])
        return None
    
    dep = r.json()
    dep_id = dep["id"]
    print(f"✅ 草稿创建成功: ID={dep_id}")
    print(f"   编辑链接: https://zenodo.org/deposit/{dep_id}")
    return dep

def upload_file(token, dep_id, filepath):
    """上传文件到草稿"""
    bucket_url = None
    
    # 获取 bucket URL
    headers = {"Authorization": f"Bearer {token}"}
    r = requests.get(f"{ZENODO_BASE}/{dep_id}", headers=headers)
    if r.status_code == 200:
        bucket_url = r.json().get("links", {}).get("bucket")
    
    if not bucket_url:
        print("❌ 无法获取 bucket URL")
        return False
    
    filename = os.path.basename(filepath)
    file_size = os.path.getsize(filepath)
    
    with open(filepath, "rb") as f:
        r = requests.put(
            f"{bucket_url}/{filename}",
            data=f,
            headers={"Content-Type": "application/octet-stream"}
        )
    
    if r.status_code == 201 or r.status_code == 200:
        print(f"✅ 文件上传成功: {filename} ({file_size/1024:.1f}KB)")
        return True
    else:
        print(f"❌ 文件上传失败: {r.status_code}")
        print(r.text[:300])
        return False

def publish(token, dep_id):
    """发布草稿"""
    headers = {"Authorization": f"Bearer {token}"}
    r = requests.post(f"{ZENODO_BASE}/{dep_id}/actions/publish", headers=headers)
    
    if r.status_code == 202:
        dep = r.json()
        doi = dep.get("doi", dep.get("metadata", {}).get("prereserve_doi", {}).get("doi"))
        concept_doi = dep.get("conceptdoi")
        print(f"🎉 发布成功!")
        print(f"📌 DOI: {doi}")
        print(f"📌 Concept DOI: {concept_doi}")
        print(f"🔗 URL: https://doi.org/{doi}")
        return doi, concept_doi
    else:
        print(f"❌ 发布失败: {r.status_code}")
        print(r.text[:500])
        return None, None

def update_card_with_doi(card_path, zenodo_doi, concept_doi):
    """将 Zenodo DOI 写回到卡片 YAML"""
    with open(card_path) as f:
        content = f.read()
    
    # 在 card: 部分添加 zenodo 字段
    zenodo_block = f"""zenodo:
  doi: "{zenodo_doi}"
  concept_doi: "{concept_doi}"
  published: "{datetime.now().strftime('%Y-%m-%d')}"
  platform: "zenodo.org"
  license: "MIT"
"""
    
    # 在 card_version 行后插入
    insert_after = "card:\n  version:"
    new_content = content.replace(insert_after, insert_after + zenodo_block, 1)
    
    if new_content != content:
        with open(card_path, "w") as f:
            f.write(new_content)
        print(f"✅ Zenodo DOI 已写入卡片: {card_path}")
        return True
    return False

def main():
    if len(sys.argv) < 2:
        print("用法: python3 zenodo_upload.py <card.yaml>")
        sys.exit(1)
    
    card_path = sys.argv[1]
    if not os.path.exists(card_path):
        print(f"❌ 文件不存在: {card_path}")
        sys.exit(1)
    
    token = get_token()
    meta = load_card(card_path)
    
    print(f"\n📤 准备上传: {meta['title']}")
    print(f"   卡片文件: {card_path}")
    print(f"   关联论文: {meta['doi']}")
    
    # 创建草稿
    dep = create_deposition(token, meta)
    if not dep:
        sys.exit(1)
    
    dep_id = dep["id"]
    
    # 上传卡片 YAML
    upload_file(token, dep_id, card_path)
    
    # 也上传一个 JSON 副本（更方便 AI 解析）
    json_path = card_path.replace(".yaml", ".json")
    with open(json_path, "w") as f:
        json.dump(meta["card_data"], f, ensure_ascii=False, indent=2)
    upload_file(token, dep_id, json_path)
    os.remove(json_path)  # 清理临时文件
    
    # 发布
    doi, concept_doi = publish(token, dep_id)
    
    if doi:
        update_card_with_doi(card_path, doi, concept_doi)
        return 0
    else:
        print("\n⚠️ 发布失败，草稿保留在 Zenodo 可手动发布")
        print(f"   编辑链接: https://zenodo.org/deposit/{dep_id}")
        return 1

if __name__ == "__main__":
    sys.exit(main())
